### ISSUE TITLE
Rendering of <select> fields should use proper values, not array indexes

### ISSUE THREAD

**Issue by ocharles** [jaspervdj/digestive-functors#38]
Currently the output of `inputSelect` (from `digestive-functors-blaze`) will look something like the following:

```
<select id="edition.country" name="edition.country">
  <option value="edition.country.0" selected="selected"></option>
  <option value="edition.country.1">United Kingdom</option>
</select>
```

The values here are only correct for as long as the country table is the same in the database. As soon as the ordering changes, those values are incorrect. In this case, the type of choices is `Maybe (Ref Country)`, which is effectively `Maybe String`, so it's important to consider how `Nothing` would be represented.

**Comment by cimmanon** [comment]
The fact that identifiers cannot contain a dot character *is* a problem.  I can imagine quite a few situations where a natural primary key might contain periods in them:

* Filenames
* Honorifics (Mr., Mrs., etc.)
* The Dewey Decimal System

Is there a way we can drop the ref path in the value without breaking existing implementations?

**Comment by jaspervdj** [comment]
We can do some normal escaping, e.g. render a normal dot to `..`?

**Comment by cimmanon** [comment]
Since the path doesn't actually serve a purpose in the value, we should really just eliminate it.  Right now, it's just noise (especially if the form is being submitted via GET) and complicates value lookup with no real benefit.

I should have a pull request soon that addresses this in a way that works with both "foo.bar.2" and "my_picture.jpg" style of submitted values.
